# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Guided Reading Collection
tagline: Life in and around Potlatch, Idaho from 1880 to 1998
description: "Potlatch Historical Society Collection Depicting life in and around Potlatch, Idaho from 1880 to 1998" 
keywords: Idaho, Latah County, Potlatch, Forests, Labor, Agriculture
csvtitle: guidedreading
email: dbecker@uidaho.edu

# url variables
url: https://dcnb.github.io
baseurl: /jekyll-collection-contentdm

# repository variables (leave blank if self-contained)
repo-type: contentdm # options[contentdm,dspace,samvera,islandora,omeka]
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: guidedread
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory
# repository-name: jekyll-collection

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'guidedreading' #should be the same as your csvtitle above
    template: 'items' 
    name: 'object-id' #name of the unique identifier in your metadata sheet
    dir: 'items' #which directory you'd like your pages generated to
    extension: 'html'
